# Generated by Django 5.0.6 on 2024-06-19 17:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litros', models.FloatField()),
                ('valor', models.FloatField()),
                ('imposto', models.FloatField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abastecimentos', to='posto_abc.bomba')),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=10)),
                ('capacidade', models.FloatField()),
                ('nivel_atual', models.FloatField()),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanques', to='posto_abc.posto')),
            ],
        ),
        migrations.AddField(
            model_name='bomba',
            name='tanque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombas', to='posto_abc.tanque'),
        ),
    ]
