# Generated by Django 5.0.6 on 2024-06-19 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto_abc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustivel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Óleo Diesel')], max_length=10)),
                ('preco_por_litro', models.FloatField()),
                ('data_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
