# Generated by Django 5.0.6 on 2024-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto_abc', '0002_precocombustivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='imposto',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='precocombustivel',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
